### PR TITLE
Add Abhishek kumar

### PR DESCRIPTION
**Pull request by abhishekkumar201005**
### Checklist for addition to Contributors list.
- [x] I have read contributing guidelines for this repository.
- [x] My code follows the style guidelines of the file to be added.
- [x] I confirm that I have added 5 or fewer technologies.
- [x] I have named this Pull Request as `Add FULLNAME`.

### CODE REVIEW

**Comment by magbanum** [comment]
Rename the title of this Pull Request as `Add Abhishek Kumar`.

**Comment by magbanum** [comment]
Your code needs to be corrected. Maximum 5 technologies are allowed so prioritize the technologies that you are well versed. Also, there are few spelling mistakes. I am not going to tell you where.

I know you are a beginner but always recheck the code and the checklist before submitting the Pull request.

**Comment by abhishekkumar201005** [comment]
> Your code needs to be corrected. Maximum 5 technologies are allowed so prioritize the technologies that you are well versed. Also, there are few spelling mistakes. I am not going to tell you where.
> 
> I know you are a beginner but always recheck the code and the checklist before submitting the Pull request.

sir, I correct the error, please check once

**Comment by magbanum** [comment]
Great, one last typing error is there. Correct the Spelling of `Python`.

**Comment by abhishekkumar201005** [comment]
> Great, one last typing error is there. Correct the Spelling of `Python`.

**Comment by abhishekkumar201005** [comment]
sorry sir for this,
github is little hard for beginner

**Comment by magbanum** [comment]
Hi @abhishekkumar201005, welcome to the community.❤

You may find this little hard but you have already started learning and that's the most important thing. Congrats on the successful Pull Request. Also, if you want to learn more about git and GitHub there do check out [Learning Lab](https://lab.github.com/).

As a next step, say hello to the community using [discussions](https://github.com/magbanum/Python-Community-Discussions/discussions).

Visit [DISCUSSIONS.md](https://github.com/magbanum/Python-Community-Discussions/blob/master/DISCUSSIONS.md#-say-hello) to know more about discussions.

Thanks,
@magbanum

**Pull request merged**
